routes/web.php
Route::match(['get', 'post'], 'home/update-notif', 'HomeController@updateNotif');
Route::match(['get', 'post'], 'home/delete-notif', 'HomeController@deleteNotif');

Route::get('user/load-data', 'UserController@loadData');
Route::get('user/json', 'UserController@json');
Route::get('user/activate/{id}', 'UserController@activate');
Route::get('user/update/{id}', 'UserController@update');
Route::get('user/deactivate/{id}', 'UserController@deactivate');
Route::get('user/{id}/reset', 'UserController@reset');
Route::get('user/cek-username-type1', 'UserController@cekusername');
Route::get('user/cek-email-type1', 'UserController@cekemail');
Route::resource('user', 'UserController');
Route::delete('user/{id}/restore', 'UserController@restore');

Route::get('autocomplete/{method}', 'AutocompleteController@search');

Route::post('role/createpermissionrole', ['as' => 'role.createpermissionrole', 'uses' => 'RoleController@createpermissionrole']);

Route::get('role/load-data', 'RoleController@loadData');
Route::get('permission-role/get/{id}/menu', 'RoleController@hakmenus');
Route::get('role/permission-role/get/{id}/menu', 'RoleController@hakmenus');
Route::resource('role', 'RoleController');
Route::delete('role/{id}/restore', 'RoleController@restore');

Route::get('permission-role/load-data', 'PermissionRoleController@loadData');
Route::resource('permission-role', 'PermissionRoleController');
Route::delete('permission-role/{id}/restore', 'PermissionRoleController@restore');

Route::get('menu/load-data', 'MenuController@loadData');
Route::resource('menu', 'MenuController');
Route::delete('menu/{id}/restore', 'MenuController@restore');

Route::get('permission/load-data', 'PermissionController@loadData');
Route::resource('permission', 'PermissionController');
Route::delete('permission/{id}/restore', 'PermissionController@restore');

Route::get('/pengaturan', 'ConfigIdController@settings')->name('settings');
Route::get('/delete-logo', 'ConfigIdController@deleteLogo');
Route::get('config-id/load-data', 'ConfigIdController@loadData');
Route::match(['get', 'post'], 'config-id/upload-foto', 'ConfigIdController@uploadFoto');
Route::match(['get', 'post'], 'config-id/check-username', 'ConfigIdController@checkUsername');
Route::match(['get', 'post'], 'config-id/check-email', 'ConfigIdController@checkEmail');
Route::match(['get', 'post'], 'config-id/check-password', 'ConfigIdController@checkPassword');
Route::get('config-id/delete-foto', 'ConfigIdController@deleteFoto');
Route::resource('config-id', 'ConfigIdController');
Route::delete('config-id/{id}/restore', 'ConfigIdController@restore');

Route::get('activity/load-data', 'ActivityLogController@loadData');
Route::get('activity/get-data', 'ActivityLogController@getData');
Route::resource('activity', 'ActivityLogController');
Route::delete('activity/{id}/restore', 'ActivityLogController@restore');

Route::get('provinsi/load-data', 'ProvinsiController@loadData');
Route::resource('provinsi', 'ProvinsiController');
Route::delete('provinsi/{id}/restore', 'ProvinsiController@restore');

Route::get('kabupaten/load-data', 'KabupatenController@loadData');
Route::resource('kabupaten', 'KabupatenController');
Route::delete('kabupaten/{id}/restore', 'KabupatenController@restore');

Route::get('kecamatan/load-data', 'KecamatanController@loadData');
Route::resource('kecamatan', 'KecamatanController');
Route::delete('kecamatan/{id}/restore', 'KecamatanController@restore');

Route::get('kelurahan/load-data', 'KelurahanController@loadData');
Route::resource('kelurahan', 'KelurahanController');
Route::delete('kelurahan/{id}/restore', 'KelurahanController@restore');

Route::get('kategori-barang/load-data', 'KategoriBarangController@loadData');
Route::resource('kategori-barang', 'KategoriBarangController');
Route::delete('kategori-barang/{id}/restore', 'KategoriBarangController@restore');
Route::get('kategori-barang/deactivate/{id}', 'KategoriBarangController@deactivate');
Route::get('kategori-barang/activate/{id}',   'KategoriBarangController@activate');

Route::get('grosir/load-data', 'GrosirController@loadData');
Route::resource('grosir', 'GrosirController');
Route::delete('grosir/{id}/restore', 'GrosirController@restore');

Route::get('barang/load-data', 'BarangController@loadData');
Route::resource('barang', 'BarangController');
Route::delete('barang/{id}/restore', 'BarangController@restore');
Route::get('barang/deactivate/{id}', 'BarangController@deactivate');
Route::get('barang/activate/{id}',   'BarangController@activate');

Route::get('skema-grosir/load-data', 'SkemaGrosirController@loadData');
Route::resource('skema-grosir', 'SkemaGrosirController');
Route::delete('skema-grosir/{id}/restore', 'SkemaGrosirController@restore');
Route::get('skema-grosir/deactivate/{id}', 'SkemaGrosirController@deactivate');
Route::get('skema-grosir/activate/{id}',   'SkemaGrosirController@activate');

Route::get('warung/load-data', 'WarungController@loadData');
Route::resource('warung', 'WarungController');
Route::delete('warung/{id}/restore', 'WarungController@restore');
Route::get('warung/deactivate/{id}', 'WarungController@deactivate');
Route::get('warung/activate/{id}',   'WarungController@activate');

Route::get('user-apk/load-data', 'UserApkController@loadData');
Route::resource('user-apk', 'UserApkController');
Route::delete('user-apk/{id}/restore', 'UserApkController@restore');

Route::get('data-diri/load-data', 'DataDiriController@loadData');
Route::resource('data-diri', 'DataDiriController');
Route::delete('data-diri/{id}/restore', 'DataDiriController@restore');

Route::get('order-datum/load-data', 'OrderDatumController@loadData');
Route::get('order-datum/detail/{id}',   'OrderDatumController@detail');
Route::get('order-datum/cetak/{id}',   'OrderDatumController@cetak');
Route::get('order-datum/confirm/{id}',   'OrderDatumController@confirm');
Route::resource('order-datum', 'OrderDatumController');
Route::delete('order-datum/{id}/restore', 'OrderDatumController@restore');

Route::get('detail-order/load-data', 'DetailOrderController@loadData');
Route::resource('detail-order', 'DetailOrderController');
Route::delete('detail-order/{id}/restore', 'DetailOrderController@restore');

Route::get('sub-kategori-barang/load-data', 'SubKategoriBarangController@loadData');
Route::resource('sub-kategori-barang', 'SubKategoriBarangController');
Route::delete('sub-kategori-barang/{id}/restore', 'SubKategoriBarangController@restore');
Route::get('sub-kategori-barang/deactivate/{id}', 'SubKategoriBarangController@deactivate');
Route::get('sub-kategori-barang/activate/{id}',   'SubKategoriBarangController@activate');

Route::get('user-apk/load-data', 'UserApkController@loadData');
Route::resource('user-apk', 'UserApkController');
Route::delete('user-apk/{id}/restore', 'UserApkController@restore');

Route::get('log-order/load-data', 'LogOrderController@loadData');
Route::resource('log-order', 'LogOrderController');
Route::delete('log-order/{id}/restore', 'LogOrderController@restore');

Route::get('minimal-order/load-data', 'MinimalOrderController@loadData');
Route::resource('minimal-order', 'MinimalOrderController');
Route::delete('minimal-order/{id}/restore', 'MinimalOrderController@restore');

Route::get('bumde/load-data', 'BumdeController@loadData');
Route::resource('bumde', 'BumdeController');
Route::delete('bumde/{id}/restore', 'BumdeController@restore');

Route::get('bumde/load-data', 'BumdeController@loadData');
Route::resource('bumde', 'BumdeController');
Route::delete('bumde/{id}/restore', 'BumdeController@restore');
Route::get('bumde/deactivate/{id}', 'BumdeController@deactivate');
Route::get('bumde/activate/{id}',   'BumdeController@activate');


Route::get('komisi/load-data', 'KomisiController@loadData');
Route::resource('komisi', 'KomisiController');
Route::delete('komisi/{id}/restore', 'KomisiController@restore');

Route::get('presentase-komisi/load-data', 'PresentaseKomisiController@loadData');
Route::resource('presentase-komisi', 'PresentaseKomisiController');
Route::delete('presentase-komisi/{id}/restore', 'PresentaseKomisiController@restore');

Route::get('paket-promo/load-data', 'PaketPromoController@loadData');
Route::resource('paket-promo', 'PaketPromoController');
Route::delete('paket-promo/{id}/restore', 'PaketPromoController@restore');
Route::get('paket-promo/deactivate/{id}', 'PaketPromoController@deactivate');
Route::get('paket-promo/activate/{id}',   'PaketPromoController@activate');
Route::get('paket-promo/detail/{id}',   'PaketPromoController@detail');

Route::get('detail-paket-promo/load-data', 'DetailPaketPromoController@loadData');
Route::resource('detail-paket-promo', 'DetailPaketPromoController');
Route::get('detail-paket-promo/load/{id}', 'DetailPaketPromoController@loadData2');
Route::delete('detail-paket-promo/{id}/restore', 'DetailPaketPromoController@restore');
Route::get('detail-paket-promo/deactivate/{id}', 'DetailPaketPromoController@deactivate');
Route::get('detail-paket-promo/activate/{id}',   'DetailPaketPromoController@activate');
Route::get('detail-paket-promo/buat/{id}',   'DetailPaketPromoController@buat');

Route::get('pembayaran/load-data', 'PembayaranController@loadData');
Route::get('pembayaran/load-data2', 'PembayaranController@loadData2');
Route::get('pembayaran/detail/{id}', 'PembayaranController@detail');
Route::get('pembayaran/simpan/{id}', 'PembayaranController@simpan');
Route::get('pembayaran/cetak/{id}', 'PembayaranController@cetak');
Route::get('pembayaran/info/', 'PembayaranController@info');
Route::resource('pembayaran', 'PembayaranController');
Route::delete('pembayaran/{id}/restore', 'PembayaranController@restore');

Route::get('warung/load-data','WarungController@loadData');
Route::resource('warung','WarungController');
Route::delete('warung/{id}/restore','WarungController@restore');
Route::get('warung/deactivate/{id}', 'WarungController@deactivate');
Route::get('warung/activate/{id}',   'WarungController@activate');

app/Models/PresentaseKomisi.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\RecordSignature;

class PresentaseKomisi extends Model {
    // use RecordSignature;
    
    public $guarded = ["id","created_at","updated_at"];
    protected $table="presentase_komisi";
    public $timestamps=true;
    protected $primaryKey = "id";
    public $incrementing = true;
    public static function findRequested()
    {
        $query = PresentaseKomisi::query();

        // search results based on user input
        \Request::input('id') and $query->where('id',\Request::input('id'));
        \Request::input('presentase_komisi') and $query->where('presentase_komisi',\Request::input('presentase_komisi'));
        \Request::input('created_at') and $query->where('created_at',\Request::input('created_at'));
        \Request::input('updated_at') and $query->where('updated_at',\Request::input('updated_at'));
        
        // sort results
        \Request::input("sort") and $query->orderBy(\Request::input("sort"),\Request::input("sortType","asc"));

        // paginate results
        return $query->paginate(15);
    }

    public static function validationRules( $attributes = null )
    {
        $rules = [
            'presentase_komisi' => 'required',
        ];

        // no list is provided
        if(!$attributes)
            return $rules;

        // a single attribute is provided
        if(!is_array($attributes))
            return [ $attributes => $rules[$attributes] ];

        // a list of attributes is provided
        $newRules = [];
        foreach ( $attributes as $attr )
            $newRules[$attr] = $rules[$attr];
        return $newRules;
    }

    public function pk(){
      return $this->{$this->primaryKey};
    }

    }

app/Http/Controllers/PresentaseKomisiController.php
<?php
namespace App\Http\Controllers;

use App\Models\PresentaseKomisi;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Datatables;

class PresentaseKomisiController extends Controller
{
    public $viewDir = "presentase_komisi";
    public $breadcrumbs = array(
         'permissions'=>array('title'=>'Presentase-komisi','link'=>"#",'active'=>false,'display'=>true),
       );

       public function __construct()
       {
           $this->middleware('permission:read-presentase-komisi');
       }

       public function index()
       {
           return $this->view( "index");
       }

       /**
        * Show the form for creating a new resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function create()
       {
           return $this->view("form",['presentaseKomisi' => new PresentaseKomisi]);
       }

       /**
        * Store a newly created resource in storage.
        *
        * @param    \Illuminate\Http\Request  $request
        * @return  \Illuminate\Http\Response
        */
       public function store( Request $request )
       {
           $this->validate($request, PresentaseKomisi::validationRules());

           $act=PresentaseKomisi::create($request->all());
           message($act,'Data Presentase Komisi berhasil ditambahkan','Data Presentase Komisi gagal ditambahkan');
           return redirect('presentase-komisi');
       }

       /**
        * Display the specified resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function show(Request $request, $kode)
       {
           $presentaseKomisi=PresentaseKomisi::find($kode);
           return $this->view("show",['presentaseKomisi' => $presentaseKomisi]);
       }

       /**
        * Show the form for editing the specified resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function edit(Request $request, $kode)
       {
           $presentaseKomisi=PresentaseKomisi::find($kode);
           return $this->view( "form", ['presentaseKomisi' => $presentaseKomisi] );
       }

       /**
        * Update the specified resource in storage.
        *
        * @param    \Illuminate\Http\Request  $request
        * @return  \Illuminate\Http\Response
        */
       public function update(Request $request, $kode)
       {
           $presentaseKomisi=PresentaseKomisi::find($kode);
           if( $request->isXmlHttpRequest() )
           {
               $data = [$request->name  => $request->value];
               $validator = \Validator::make( $data, PresentaseKomisi::validationRules( $request->name ) );
               if($validator->fails())
                   return response($validator->errors()->first( $request->name),403);
               $presentaseKomisi->update($data);
               return "Record updated";
           }
           $this->validate($request, PresentaseKomisi::validationRules());

           $act=$presentaseKomisi->update($request->all());
           message($act,'Data Presentase Komisi berhasil diupdate','Data Presentase Komisi gagal diupdate');

           return redirect('/presentase-komisi');
       }

       /**
        * Remove the specified resource from storage.
        *
        * @return  \Illuminate\Http\Response
        */
       public function destroy(Request $request, $kode)
       {
           $presentaseKomisi=PresentaseKomisi::find($kode);
           $act=false;
           try {
               $act=$presentaseKomisi->forceDelete();
           } catch (\Exception $e) {
               $presentaseKomisi=PresentaseKomisi::find($presentaseKomisi->pk());
               $act=$presentaseKomisi->delete();
           }
       }

       protected function view($view, $data = [])
       {
           return view($this->viewDir.".".$view, $data);
       }
       public function loadData()
       {
           $GLOBALS['nomor']=\Request::input('start',1)+1;
           $dataList = PresentaseKomisi::select('*');
           if (request()->get('status') == 'trash') {
               $dataList->onlyTrashed();
           }
           return Datatables::of($dataList)
               ->addColumn('nomor',function($kategori){
                   return $GLOBALS['nomor']++;
               })
               ->addColumn('action', function ($data) {
                   $edit=url("presentase-komisi/".$data->pk())."/edit";
                   $delete=url("presentase-komisi/".$data->pk());
                 $content = '';
                  $content .= "<a onclick='show_modal(\"$edit\")' class='btn btn-sm btn-icon btn-pure btn-default on-default edit-row ' data-toggle='tooltip' data-original-title='Edit'><i class='icon md-edit' aria-hidden='true'></i></a>";
                  $content .= " <a onclick='hapus(\"$delete\")' class='btn btn-sm btn-icon btn-pure btn-default on-default remove-row' data-toggle='tooltip' data-original-title='Remove'><i class='icon md-delete' aria-hidden='true'></i></a>";

                   return $content;
               })
               ->make(true);
       }
         }

resources/views/presentase_komisi/form.blade.php
<div class="modal-dialog modal-simple">

		{{ Form::model($presentaseKomisi,array('route' => array((!$presentaseKomisi->exists) ? 'presentase-komisi.store':'presentase-komisi.update',$presentaseKomisi->pk()),
	        'class'=>'modal-content','id'=>'presentase-komisi-form','method'=>(!$presentaseKomisi->exists) ? 'POST' : 'PUT')) }}

		<div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h4 class="modal-title" id="formModalLabel">{{ ($presentaseKomisi->exists?'Edit':'Tambah').' Presentase Komisi' }}</h4>
    </div>
    <div class="modal-body">
																				        {!! App\Console\Commands\Generator\Form::input('presentase_komisi','text')->model($presentaseKomisi)->show() !!}
																												<div class="col-md-12 float-right">
					<div class="text-right">
						<button class="btn btn-primary" id="simpan">Simpan</button>
					</div>
				</div>
		</div>

	    {{ Form::close() }}
</div>


<script type="text/javascript">
$(document).ready(function(){
	$('#presentase-komisi-form').formValidation({
	  framework: "bootstrap4",
	  button: {
	    selector: "#simpan",
	    disabled: "disabled"
	  },
	  icon: null,
	  fields: {
	presentase_komisi : { validators: {
				        notEmpty: {
				          message: 'Kolom presentase_komisi tidak boleh kosong'
							}
						}
					}
},
err: {
	clazz: 'invalid-feedback'
},
control: {
	// The CSS class for valid control
	valid: 'is-valid',

	// The CSS class for invalid control
	invalid: 'is-invalid'
},
row: {
	invalid: 'has-danger'
}
});
	

});
</script>

resources/views/presentase_komisi/index.blade.php
@extends('layouts.app')

@section('content')
   <div class="page-header">
     <h1 class="page-title">Presentase Komisi</h1>
      @include('layouts.inc.breadcrumb')
     <div class="page-header-actions">
     <a class="btn btn-block btn-primary data-modal" id="data-modal" href="#" onclick="show_modal('{{ route('presentase-komisi.create') }}')" >Tambah</a>
     </div>
   </div>
   <div class="page-content">
     <!-- Panel Table Tools -->
     <div class="panel">
       <header class="panel-heading">
         <div class="form-group col-md-12">
           <div class="form-group">
         <!-- <h3 class="panel-title">Table Tools</h3> -->

           </div>
         </div>
       </header>
       <div class="panel-body">
         <!-- <table class="table table-bordered" id="users-table">

         </table> -->
         <table class="table table-hover dataTable table-striped w-full" id="presentase-komisi-table">
           <thead>
               <tr>
                 <th>No</th>
                                           <th>Presentase Komisi (%)</th>
                                    <th>Created At</th>
                             <th>Action</th>
               </tr>
           </thead>
         </table>
       </div>
     </div>
     <!-- End Panel Table Tools -->
 </div>
 <div class="modal fade" id="formModal" aria-hidden="true" aria-labelledby="formModalLabel" role="dialog" tabindex="-1">
 </div>

@endsection

@push('js')
<script type="text/javascript">
$(function() {
  $('.trash-ck').click(function(){
    if ($('.trash-ck').prop('checked')) {
      document.location = '{{ url("presentase-komisi?status=trash") }}';
    } else {
      document.location = '{{ url("presentase-komisi") }}';
    }
  });
    $('#presentase-komisi-table').DataTable({
      stateSave: true,
    processing : true,
    serverSide : true,
    pageLength:20,
        ajax : {
                  url:"{{ url('presentase-komisi/load-data') }}",
                data: function (d) {

                }
      },
        columns: [
          { data: 'nomor', name: 'nomor',searchable:false,orderable:false },
                                      { data: 'presentase_komisi', name: 'presentase_komisi' },
                      { data: 'created_at', name: 'created_at' },
                      { data: 'action', name: 'action', orderable: false, searchable: false },
      ],
      language: {
            lengthMenu : '{{ "Menampilkan _MENU_ data" }}',
            zeroRecords : '{{ "Data tidak ditemukan" }}' ,
            info : '{{ "_PAGE_ dari _PAGES_ halaman" }}',
            infoEmpty : '{{ "Data tidak ditemukan" }}',
            infoFiltered : '{{ "(Penyaringan dari _MAX_ data)" }}',
            loadingRecords : '{{ "Memuat data dari server" }}' ,
            processing :    '{{ "Memuat data data" }}',
            search :        '{{ "Pencarian:" }}',
            paginate : {
                first :     '{{ "<" }}' ,
                last :      '{{ ">" }}' ,
                next :      '{{ ">>" }}',
                previous :  '{{ "<<" }}'
            }
        },
        aoColumnDefs: [{
          bSortable: false,
          aTargets: [-1]
        }],
        iDisplayLength: 5,
        aLengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
        // sDom: '<"dt-panelmenu clearfix"Bfr>t<"dt-panelfooter clearfix"ip>',
        // buttons: ['copy', 'excel', 'csv', 'pdf', 'print'],
    });
});
</script>
@endpush