routes/web.php
Route::match(['get', 'post'], 'home/update-notif', 'HomeController@updateNotif');
Route::match(['get', 'post'], 'home/delete-notif', 'HomeController@deleteNotif');

Route::get('user/load-data', 'UserController@loadData');
Route::get('user/json', 'UserController@json');
Route::get('user/activate/{id}', 'UserController@activate');
Route::get('user/update/{id}', 'UserController@update');
Route::get('user/deactivate/{id}', 'UserController@deactivate');
Route::get('user/{id}/reset', 'UserController@reset');
Route::get('user/cek-username-type1', 'UserController@cekusername');
Route::get('user/cek-email-type1', 'UserController@cekemail');
Route::resource('user', 'UserController');
Route::delete('user/{id}/restore', 'UserController@restore');

Route::get('autocomplete/{method}', 'AutocompleteController@search');

Route::post('role/createpermissionrole', ['as' => 'role.createpermissionrole', 'uses' => 'RoleController@createpermissionrole']);

Route::get('role/load-data', 'RoleController@loadData');
Route::get('permission-role/get/{id}/menu', 'RoleController@hakmenus');
Route::get('role/permission-role/get/{id}/menu', 'RoleController@hakmenus');
Route::resource('role', 'RoleController');
Route::delete('role/{id}/restore', 'RoleController@restore');

Route::get('permission-role/load-data', 'PermissionRoleController@loadData');
Route::resource('permission-role', 'PermissionRoleController');
Route::delete('permission-role/{id}/restore', 'PermissionRoleController@restore');

Route::get('menu/load-data', 'MenuController@loadData');
Route::resource('menu', 'MenuController');
Route::delete('menu/{id}/restore', 'MenuController@restore');

Route::get('permission/load-data', 'PermissionController@loadData');
Route::resource('permission', 'PermissionController');
Route::delete('permission/{id}/restore', 'PermissionController@restore');

Route::get('/pengaturan', 'ConfigIdController@settings')->name('settings');
Route::get('/delete-logo', 'ConfigIdController@deleteLogo');
Route::get('config-id/load-data', 'ConfigIdController@loadData');
Route::match(['get', 'post'], 'config-id/upload-foto', 'ConfigIdController@uploadFoto');
Route::match(['get', 'post'], 'config-id/check-username', 'ConfigIdController@checkUsername');
Route::match(['get', 'post'], 'config-id/check-email', 'ConfigIdController@checkEmail');
Route::match(['get', 'post'], 'config-id/check-password', 'ConfigIdController@checkPassword');
Route::get('config-id/delete-foto', 'ConfigIdController@deleteFoto');
Route::resource('config-id', 'ConfigIdController');
Route::delete('config-id/{id}/restore', 'ConfigIdController@restore');

Route::get('activity/load-data', 'ActivityLogController@loadData');
Route::get('activity/get-data', 'ActivityLogController@getData');
Route::resource('activity', 'ActivityLogController');
Route::delete('activity/{id}/restore', 'ActivityLogController@restore');

Route::get('provinsi/load-data', 'ProvinsiController@loadData');
Route::resource('provinsi', 'ProvinsiController');
Route::delete('provinsi/{id}/restore', 'ProvinsiController@restore');

Route::get('kabupaten/load-data', 'KabupatenController@loadData');
Route::resource('kabupaten', 'KabupatenController');
Route::delete('kabupaten/{id}/restore', 'KabupatenController@restore');

Route::get('kecamatan/load-data', 'KecamatanController@loadData');
Route::resource('kecamatan', 'KecamatanController');
Route::delete('kecamatan/{id}/restore', 'KecamatanController@restore');

Route::get('kelurahan/load-data', 'KelurahanController@loadData');
Route::resource('kelurahan', 'KelurahanController');
Route::delete('kelurahan/{id}/restore', 'KelurahanController@restore');

Route::get('kategori-barang/load-data', 'KategoriBarangController@loadData');
Route::resource('kategori-barang', 'KategoriBarangController');
Route::delete('kategori-barang/{id}/restore', 'KategoriBarangController@restore');
Route::get('kategori-barang/deactivate/{id}', 'KategoriBarangController@deactivate');
Route::get('kategori-barang/activate/{id}',   'KategoriBarangController@activate');

Route::get('grosir/load-data', 'GrosirController@loadData');
Route::resource('grosir', 'GrosirController');
Route::delete('grosir/{id}/restore', 'GrosirController@restore');

Route::get('barang/load-data', 'BarangController@loadData');
Route::resource('barang', 'BarangController');
Route::delete('barang/{id}/restore', 'BarangController@restore');
Route::get('barang/deactivate/{id}', 'BarangController@deactivate');
Route::get('barang/activate/{id}',   'BarangController@activate');

Route::get('skema-grosir/load-data', 'SkemaGrosirController@loadData');
Route::resource('skema-grosir', 'SkemaGrosirController');
Route::delete('skema-grosir/{id}/restore', 'SkemaGrosirController@restore');
Route::get('skema-grosir/deactivate/{id}', 'SkemaGrosirController@deactivate');
Route::get('skema-grosir/activate/{id}',   'SkemaGrosirController@activate');

Route::get('warung/load-data', 'WarungController@loadData');
Route::resource('warung', 'WarungController');
Route::delete('warung/{id}/restore', 'WarungController@restore');
Route::get('warung/deactivate/{id}', 'WarungController@deactivate');
Route::get('warung/activate/{id}',   'WarungController@activate');

Route::get('user-apk/load-data', 'UserApkController@loadData');
Route::resource('user-apk', 'UserApkController');
Route::delete('user-apk/{id}/restore', 'UserApkController@restore');

Route::get('data-diri/load-data', 'DataDiriController@loadData');
Route::resource('data-diri', 'DataDiriController');
Route::delete('data-diri/{id}/restore', 'DataDiriController@restore');

Route::get('order-datum/load-data', 'OrderDatumController@loadData');
Route::get('order-datum/detail/{id}',   'OrderDatumController@detail');
Route::get('order-datum/cetak/{id}',   'OrderDatumController@cetak');
Route::get('order-datum/confirm/{id}',   'OrderDatumController@confirm');
Route::resource('order-datum', 'OrderDatumController');
Route::delete('order-datum/{id}/restore', 'OrderDatumController@restore');

Route::get('detail-order/load-data', 'DetailOrderController@loadData');
Route::resource('detail-order', 'DetailOrderController');
Route::delete('detail-order/{id}/restore', 'DetailOrderController@restore');

Route::get('sub-kategori-barang/load-data', 'SubKategoriBarangController@loadData');
Route::resource('sub-kategori-barang', 'SubKategoriBarangController');
Route::delete('sub-kategori-barang/{id}/restore', 'SubKategoriBarangController@restore');
Route::get('sub-kategori-barang/deactivate/{id}', 'SubKategoriBarangController@deactivate');
Route::get('sub-kategori-barang/activate/{id}',   'SubKategoriBarangController@activate');

Route::get('user-apk/load-data', 'UserApkController@loadData');
Route::resource('user-apk', 'UserApkController');
Route::delete('user-apk/{id}/restore', 'UserApkController@restore');

Route::get('log-order/load-data', 'LogOrderController@loadData');
Route::resource('log-order', 'LogOrderController');
Route::delete('log-order/{id}/restore', 'LogOrderController@restore');

Route::get('minimal-order/load-data', 'MinimalOrderController@loadData');
Route::resource('minimal-order', 'MinimalOrderController');
Route::delete('minimal-order/{id}/restore', 'MinimalOrderController@restore');

Route::get('bumde/load-data', 'BumdeController@loadData');
Route::resource('bumde', 'BumdeController');
Route::delete('bumde/{id}/restore', 'BumdeController@restore');

Route::get('bumde/load-data', 'BumdeController@loadData');
Route::resource('bumde', 'BumdeController');
Route::delete('bumde/{id}/restore', 'BumdeController@restore');
Route::get('bumde/deactivate/{id}', 'BumdeController@deactivate');
Route::get('bumde/activate/{id}',   'BumdeController@activate');


Route::get('komisi/load-data', 'KomisiController@loadData');
Route::resource('komisi', 'KomisiController');
Route::delete('komisi/{id}/restore', 'KomisiController@restore');

Route::get('presentase-komisi/load-data', 'PresentaseKomisiController@loadData');
Route::resource('presentase-komisi', 'PresentaseKomisiController');
Route::delete('presentase-komisi/{id}/restore', 'PresentaseKomisiController@restore');

Route::get('paket-promo/load-data', 'PaketPromoController@loadData');
Route::resource('paket-promo', 'PaketPromoController');
Route::delete('paket-promo/{id}/restore', 'PaketPromoController@restore');
Route::get('paket-promo/deactivate/{id}', 'PaketPromoController@deactivate');
Route::get('paket-promo/activate/{id}',   'PaketPromoController@activate');
Route::get('paket-promo/detail/{id}',   'PaketPromoController@detail');

Route::get('detail-paket-promo/load-data', 'DetailPaketPromoController@loadData');
Route::resource('detail-paket-promo', 'DetailPaketPromoController');
Route::get('detail-paket-promo/load/{id}', 'DetailPaketPromoController@loadData2');
Route::delete('detail-paket-promo/{id}/restore', 'DetailPaketPromoController@restore');
Route::get('detail-paket-promo/deactivate/{id}', 'DetailPaketPromoController@deactivate');
Route::get('detail-paket-promo/activate/{id}',   'DetailPaketPromoController@activate');
Route::get('detail-paket-promo/buat/{id}',   'DetailPaketPromoController@buat');

Route::get('pembayaran/load-data', 'PembayaranController@loadData');
Route::get('pembayaran/load-data2', 'PembayaranController@loadData2');
Route::get('pembayaran/detail/{id}', 'PembayaranController@detail');
Route::get('pembayaran/simpan/{id}', 'PembayaranController@simpan');
Route::get('pembayaran/cetak/{id}', 'PembayaranController@cetak');
Route::get('pembayaran/info/', 'PembayaranController@info');
Route::resource('pembayaran', 'PembayaranController');
Route::delete('pembayaran/{id}/restore', 'PembayaranController@restore');

Route::get('warung/load-data','WarungController@loadData');
Route::resource('warung','WarungController');
Route::delete('warung/{id}/restore','WarungController@restore');
Route::get('warung/deactivate/{id}', 'WarungController@deactivate');
Route::get('warung/activate/{id}',   'WarungController@activate');

app/Http/Controllers/BumdeController.php
<?php
namespace App\Http\Controllers;

use App\Models\Bumde;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Datatables;

class BumdeController extends Controller
{
    public $viewDir = "bumde";
    public $breadcrumbs = array(
         'permissions'=>array('title'=>'Bumdes','link'=>"#",'active'=>false,'display'=>true),
       );

       public function __construct()
       {
           $this->middleware('permission:read-bumdes');
       }

       public function index()
       {
           return $this->view( "index");
       }

       /**
        * Show the form for creating a new resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function create()
       {
           return $this->view("form",['bumde' => new Bumde]);
       }

       /**
        * Store a newly created resource in storage.
        *
        * @param    \Illuminate\Http\Request  $request
        * @return  \Illuminate\Http\Response
        */
       public function store( Request $request )
       {
        //    dd($request->all());
           $this->validate($request, Bumde::validationRules());

           $act=Bumde::create($request->all());
           message($act,'Data Bumdes berhasil ditambahkan','Data Bumdes gagal ditambahkan');
           return redirect('bumde');
       }

       /**
        * Display the specified resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function show(Request $request, $kode)
       {
           $bumde=Bumde::find($kode);
           return $this->view("show",['bumde' => $bumde]);
       }

       /**
        * Show the form for editing the specified resource.
        *
        * @return  \Illuminate\Http\Response
        */
       public function edit(Request $request, $kode)
       {
           $bumde=Bumde::find($kode);
           return $this->view( "form", ['bumde' => $bumde] );
       }

       /**
        * Update the specified resource in storage.
        *
        * @param    \Illuminate\Http\Request  $request
        * @return  \Illuminate\Http\Response
        */
       public function update(Request $request, $kode)
       {
           $bumde=Bumde::find($kode);
           if( $request->isXmlHttpRequest() )
           {
               $data = [$request->name  => $request->value];
               $validator = \Validator::make( $data, Bumde::validationRules( $request->name ) );
               if($validator->fails())
                   return response($validator->errors()->first( $request->name),403);
               $bumde->update($data);
               return "Record updated";
           }
           $this->validate($request, Bumde::validationRules());

           $act=$bumde->update($request->all());
           message($act,'Data Bumdes berhasil diupdate','Data Bumdes gagal diupdate');

           return redirect('/bumde');
       }

       /**
        * Remove the specified resource from storage.
        *
        * @return  \Illuminate\Http\Response
        */
       public function destroy(Request $request, $kode)
       {
           $bumde=Bumde::find($kode);
           $act=false;
           try {
               $act=$bumde->forceDelete();
           } catch (\Exception $e) {
               $bumde=Bumde::find($bumde->pk());
               $act=$bumde->delete();
           }
       }

       protected function view($view, $data = [])
       {
           return view($this->viewDir.".".$view, $data);
       }
       public function loadData()
       {
           $GLOBALS['nomor']=\Request::input('start',1)+1;
           $dataList = Bumde::select('*');
           if (request()->get('status') == 'trash') {
               $dataList->onlyTrashed();
           }
           return Datatables::of($dataList)
               ->addColumn('nomor',function($kategori){
                   return $GLOBALS['nomor']++;
               })
               ->addColumn('status', function ($data) {
                //    dd($data->status_aktif);
                if(isset($data->status_aktif))
                {
                 return array('id'=>$data->pk(),'status_aktif'=>$data->status_aktif);
                }else
                {
                 return null;
                }
                
            })
            ->addColumn('kelurahan',function($data){
                return $data->kelurahan->kelurahan;
            })
               ->addColumn('action', function ($data) {
                   $edit=url("bumde/".$data->pk())."/edit";
                   $delete=url("bumde/".$data->pk());
                 $content = '';
                  $content .= "<a onclick='show_modal(\"$edit\")' class='btn btn-sm btn-icon btn-pure btn-default on-default edit-row ' data-toggle='tooltip' data-original-title='Edit'><i class='icon md-edit' aria-hidden='true'></i></a>";
                  $content .= " <a onclick='hapus(\"$delete\")' class='btn btn-sm btn-icon btn-pure btn-default on-default remove-row' data-toggle='tooltip' data-original-title='Remove'><i class='icon md-delete' aria-hidden='true'></i></a>";

                   return $content;
               })
               ->make(true);
       }
       public function activate(Request $request, $kode)
       {
        // dd($kode);
            $kategoriBarang= Bumde::find($kode);
            $data=array(
            'status_aktif'=>'Y',
            );
            
            $status=$kategoriBarang->update($data);
            message($status,'Data Bumdes Berhasil Diaktifkan Kembali','Data Bumdes Gagal Diaktifkan Kembali');
            return redirect('/bumde');
       } 

        public function deactivate(Request $request, $kode){
        
            $kategoriBarang=Bumde::find($kode);
            $data=array('status_aktif'=>'N',);
       
            $status=$kategoriBarang->update($data);
            message($status,'Data Bumdes Berhasil Dinonaktifkan','Data Bumdes Gagal Dinonaktifkan');
        
            return redirect('/bumde');
       }
}

resources/views/bumde/form.blade.php
<div class="modal-dialog modal-simple">

		{{ Form::model($bumde,array('route' => array((!$bumde->exists) ? 'bumde.store':'bumde.update',$bumde->pk()),
	        'class'=>'modal-content','id'=>'bumde-form','method'=>(!$bumde->exists) ? 'POST' : 'PUT')) }}

		<div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h4 class="modal-title" id="formModalLabel">{{ ($bumde->exists?'Edit':'Tambah').' Bumdes' }}</h4>
    </div>
    <div class="modal-body">
																				        {!! App\Console\Commands\Generator\Form::input('bumdes','text')->model($bumde)->show() !!}
																        {!! App\Console\Commands\Generator\Form::input('nama_koordinator','text')->model($bumde)->show() !!}
																        {!! App\Console\Commands\Generator\Form::textarea( 'alamat' )->model($bumde)->show() !!}
																        {!! App\Console\Commands\Generator\Form::input('id_kelurahan','hidden')->model($bumde)->showHidden() !!}
{!! App\Console\Commands\Generator\Form::autocomplete('kelurahan',array('value'=>$bumde->exists?(isset($bumde->kelurahan)?$bumde->kelurahan->kelurahan:null):null))->model(null)->show() !!}
	<div class="form-group row">
			<label for="provinsi" class="col-form-label col-md-3">Status</label>
			<div class="col-md-7">
				<label class="form-check-label">
					<input type="radio" class="form-check-input" name="status_aktif" value='Y' checked>Aktif
				</label>
				<label class="form-check-label">
					<input type="radio" class="form-check-input" name="status_aktif" value='N' @if ($bumde->status_aktif=='N')
					checked
					@endif>Tidak Aktif
				</label>
			</div>
		</div>
																												<div class="col-md-12 float-right">
					<div class="text-right">
						<button class="btn btn-primary" id="simpan">Simpan</button>
					</div>
				</div>
		</div>

	    {{ Form::close() }}
</div>


<script type="text/javascript">
$(document).ready(function(){
	$('#bumde-form').formValidation({
	  framework: "bootstrap4",
	  button: {
	    selector: "#simpan",
	    disabled: "disabled"
	  },
	  icon: null,
	  fields: {
	bumdes : { validators: {
				        notEmpty: {
				          message: 'Kolom bumdes tidak boleh kosong'
							}
						}
					},nama_koordinator : { validators: {
				        notEmpty: {
				          message: 'Kolom nama_koordinator tidak boleh kosong'
							}
						}
					},status_aktif : { validators: {
				        notEmpty: {
				          message: 'Kolom status_aktif tidak boleh kosong'
							}
						}
					}
},
err: {
	clazz: 'invalid-feedback'
},
control: {
	// The CSS class for valid control
	valid: 'is-valid',

	// The CSS class for invalid control
	invalid: 'is-invalid'
},
row: {
	invalid: 'has-danger'
}
});
	
					var kelurahanEngine = new Bloodhound({
							datumTokenizer: function(d) { return d.tokens; },
							queryTokenizer: Bloodhound.tokenizers.whitespace,
							cache: false,
							remote: {
								url: '{{ url("autocomplete/kelurahan") }}?q=%QUERY',
								wildcard: "%QUERY"
							}
						});

						$("#kelurahan").typeahead({
									hint: true,
									highlight: true,
									minLength: 1
							},
							{
									source: kelurahanEngine.ttAdapter(),
									name: "kelurahan",
									displayKey: "kelurahan",
									templates: {
										suggestion: function(data){
											return Handlebars.compile([
																"<div class=\"tt-dataset\">",
																		"<div>@{{kelurahan}}</div>",
																"</div>",
														].join(""))(data);
										},
											empty: [
													"<div>kelurahan tidak ditemukan</div>"
											]
									}
							}).bind("typeahead:selected", function(obj, datum, name) {
								$("#id_kelurahan").val(datum.id);
							}).bind("typeahead:change", function(obj, datum, name) {

							});
					

});
</script>

resources/views/bumde/index.blade.php
@extends('layouts.app')

@section('content')
   <div class="page-header">
     <h1 class="page-title">Bumdes</h1>
      @include('layouts.inc.breadcrumb')
     <div class="page-header-actions">
     <a class="btn btn-block btn-primary data-modal" id="data-modal" href="#" onclick="show_modal('{{ route('bumde.create') }}')" >Tambah</a>
     </div>
   </div>
   <div class="page-content">
     <!-- Panel Table Tools -->
     <div class="panel">
       <header class="panel-heading">
         <div class="form-group col-md-12">
           <div class="form-group">
         <!-- <h3 class="panel-title">Table Tools</h3> -->

           </div>
         </div>
       </header>
       <div class="panel-body">
         <!-- <table class="table table-bordered" id="users-table">

         </table> -->
         <table class="table table-hover dataTable table-striped w-full" id="bumde-table">
           <thead>
               <tr>
                 <th>No</th>
                                    <th>Nama Bumdes</th>
                                    <th>Nama Koordinator</th>
                                    <th>Alamat</th>
                                    <th>Kelurahan</th>
                                    <th>Status</th>
                                    <!-- <th>created_at</th> -->
                             <th>Action</th>
               </tr>
           </thead>
         </table>
       </div>
     </div>
     <!-- End Panel Table Tools -->
 </div>
 <div class="modal fade" id="formModal" aria-hidden="true" aria-labelledby="formModalLabel" role="dialog" tabindex="-1">
 </div>

@endsection

@push('js')
<script type="text/javascript">
$(function() {
  $('.trash-ck').click(function(){
    if ($('.trash-ck').prop('checked')) {
      document.location = '{{ url("bumde?status=trash") }}';
    } else {
      document.location = '{{ url("bumde") }}';
    }
  });
    $('#bumde-table').DataTable({
      stateSave: true,
    processing : true,
    serverSide : true,
    pageLength:20,
        ajax : {
                  url:"{{ url('bumde/load-data') }}",
                data: function (d) {

                }
      },
        columns: [
          { data: 'nomor', name: 'nomor',searchable:false,orderable:false },
                                      { data: 'bumdes', name: 'bumdes' },
                      { data: 'nama_koordinator', name: 'nama_koordinator' },
                      { data: 'alamat', name: 'alamat' },
                      { data: 'kelurahan', name: 'kelurahan' },
                      { data: 'status', name: 'Status', searchable:false,orderable:false , "render":function(data,type,row){
                        // console.log(data.status_aktif);
                                        if(data.status_aktif =='Y')
                                              {
                                                return '<a class="btn btn-success btn-xs"  style="color:white; font-family:Arial" title="Nonaktifkan " onclick="con(\'' + data.id + '\',\'' + data.status_aktif + '\') ">Aktif</a>';
                                              }
                                              else
                                              {
                                                return '<a class="btn btn-danger btn-xs"  style="color:white;font-family:Arial" title="Aktifkan" onclick="con(\'' + data.id + '\',\'' + data.status_aktif + '\') ">Tidak Aktif</a>';
                                              }
                                            }						   
                                        },
                      // { data: 'created_at', name: 'created_at' },
                      { data: 'action', name: 'action', orderable: false, searchable: false },
      ],
      language: {
            lengthMenu : '{{ "Menampilkan _MENU_ data" }}',
            zeroRecords : '{{ "Data tidak ditemukan" }}' ,
            info : '{{ "_PAGE_ dari _PAGES_ halaman" }}',
            infoEmpty : '{{ "Data tidak ditemukan" }}',
            infoFiltered : '{{ "(Penyaringan dari _MAX_ data)" }}',
            loadingRecords : '{{ "Memuat data dari server" }}' ,
            processing :    '{{ "Memuat data data" }}',
            search :        '{{ "Pencarian:" }}',
            paginate : {
                first :     '{{ "<" }}' ,
                last :      '{{ ">" }}' ,
                next :      '{{ ">>" }}',
                previous :  '{{ "<<" }}'
            }
        },
        aoColumnDefs: [{
          bSortable: false,
          aTargets: [-1]
        }],
        iDisplayLength: 5,
        aLengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
        // sDom: '<"dt-panelmenu clearfix"Bfr>t<"dt-panelfooter clearfix"ip>',
        // buttons: ['copy', 'excel', 'csv', 'pdf', 'print'],
    });
});
function con(id,status)
{
  if(status=='Y')
  {
    swal({
        title: "Apakah anda yakin?",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes",
        closeOnConfirm: false
    }, function (isConfirm) {
        if (!isConfirm) return;
        window.location.href = "{{ url('bumde/deactivate/')}}/"+id+"";
    });
  }
  else
    {
      swal({
          title: "Apakah anda yakin?",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes",
          closeOnConfirm: false
      }, function (isConfirm) {
          if (!isConfirm) return;
          window.location.href = "{{ url('bumde/activate/')}}/"+id+"";
      });
    }
  
}
</script>
@endpush